### PR TITLE
added Consolidate all agile content

### PR DESCRIPTION
**Pull request by nkululek0**
Related issues: [https://github.com/Umuzi-org/ACN-syllabus/issues/55]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by sheenarbw — CHANGES_REQUESTED** [review]
I think you just copy-pasted things around. What we need you to do is move stuff. If we have multiple copies of the same files then that would be a confusing thing.

Our documentation is code. It should be DRY.

**Comment by nkululek0** [comment]
> I think you just copy-pasted things around. What we need you to do is move stuff. If we have multiple copies of the same files then that would be a confusing thing.
> 
> Our documentation is code. It should be DRY.

Fixed errors related to this matter

**Comment by sheenarbw** [comment]
Please run the linter and make sure it still works. I'm certain that there will now be broken links: The content has moved so everything that links to that content should be updated.

**Comment by nkululek0** [comment]
Ran both linter and hugo, works perfectly on my machine

**Review by sheenarbw — CHANGES_REQUESTED** [review]
Are you sure the linter ran fine? I just ran it against your branch and got this output:

```
(nkululek0-ACN-syllabus) ➜  nkululek0-ACN-syllabus git:(consolidate-all-agile-content) ✗ python lint.py
Building sites … 


                   |  EN   
+------------------+------+
  Pages            | 1284  
  Paginator pages  |    0  
  Non-page files   |  415  
  Static files     |   74  
  Processed images |    0  
  Aliases          |    0  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 15150 ms
public/syllabuses/web-dev-no-nqf/index.html:  <span class="contentlink-missing" data="workshops/agile-recap/"
public/syllabuses/web-dev-no-nqf/index.html:  <span class="contentlink-missing" data="topics/agile-scrum"
public/syllabuses/web-dev-no-nqf/index.html:  <span class="contentlink-missing" data="workshops/agile-scrum/"
public/syllabuses/web-dev/index.html:  <span class="contentlink-missing" data="topics/agile-scrum"
public/syllabuses/web-dev/index.html:  <span class="contentlink-missing" data="workshops/agile-scrum/"
public/syllabuses/web-dev/index.html:  <span class="contentlink-missing" data="workshops/agile-recap/"
public/syllabuses/_web-frontend-foundations/index.html:  <span class="contentlink-missing" data="topics/agile-scrum"
public/syllabuses/java/index.html:  <span class="contentlink-missing" data="topics/agile-scrum"
public/syllabuses/java/index.html:  <span class="contentlink-missing" data="workshops/agile-scrum/"
public/syllabuses/data-eng/index.html:  <span class="contentlink-missing" data="topics/agile-scrum"
public/syllabuses/data-eng/index.html:  <span class="contentlink-missing" data="workshops/agile-scrum/"
public/syllabuses/data-eng/index.html:  <span class="contentlink-missing" data="workshops/agile-recap/"
public/syllabuses/data-sci/index.html:  <span class="contentlink-missing" data="topics/agile-scrum"
public/syllabuses/data-sci/index.html:  <span class="contentlink-missing" data="workshops/agile-scrum/"
public/syllabuses/data-sci/index.html:  <span class="contentlink-missing" data="workshops/agile-scrum/"
public/syllabuses/data-sci/index.html:  <span class="contentlink-missing" data="workshops/agile-recap/"
```

All those missing links are a problem. We need all the links to point to stuff that exists. So if content gets moved then all the links that point to that content needs to get updated.

**Comment by nkululek0** [comment]
My mistake, just realised that I didn't commit the modified syllabus content
It is done now

**Review by sheenarbw — CHANGES_REQUESTED** [review]
Ok, you are getting there. But now there are merge conflicts! Can you pull the latest version of the develop branch. And then either merge it into your branch or do a rebase. Once the conflics are sorted out we should be good to go

**Comment by nkululek0** [comment]
I have done a git pull and merged the develop with my branch
How will I know if the conflicts have been fixed since they don't show on my sdie

**Review by sheenarbw — APPROVED** [review]

**Pull request merged**
