### PR TITLE
ACN: Bootcamp Writing Assignment

### PR DESCRIPTION
**Pull request by asradebe**
Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by kaleem99 — COMMENTED** [review]
Hi, Asanda looks good but pls make sure to tick the checkbox and run linter to check for errors and check if the Hugo server is running.

**Comment by asradebe** [comment]
@kaleem99 i ran the linter. It looks fine on my side. Is it fine on your side?

**Review by kaleem99 — DISMISSED** [review]

**Comment by kaleem99** [comment]
> @kaleem99 i ran the linter. It looks fine on my side. Is it fine on your side?

looks good.

**Comment by asradebe** [comment]
will open new pull request

**Pull request closed without merging**
