### PR TITLE
Create "##Instructions for reviewer" for project Multivariate Linear Regression #94

### LINKED ISSUE #94: Create "##Instructions for reviewer" for project Multivariate Linear Regression
Please add a section to the bottom of this project's _index.md file.
The section heading should be EXACTLY "## Instructions for reviewer"

Basically we have to set reviewers up for success by telling them what success looks like and what to pay attention to when reviewing this project submission.

Description:

 

- [ ] Look at a bunch of old reviews for this project for each cohort

 

- [ ] Find the common feedback [This should help you get an idea of what instructions to create]

 

- [ ] Write them out clearly

 

- [ ] The section heading should be EXACTLY "## Instructions for reviewer"

### PR DESCRIPTION
**Pull request by TheAbstract**
Related issues: #94 

## Description:

What are you up to? Fill us in :) 
Added instructions for reviewer.

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by ry-oc** [comment]
@TheAbstract , @Andy-Nkumane or @EckardBerry should probably be the first review on this

**Review by EckardBerry — CHANGES_REQUESTED** [review]
Hello

Just two remarks:

1. Line 88 reads "EDA means actually analysing the data; it's now enough to create a graph..."
   Should the 'now' not be a 'not'?

2. Should 'multicollinearity' in line 92 not be 'multi-collinearity'?

**Review by EckardBerry — APPROVED** [review]

**Review by ry-oc — APPROVED** [review]

**Review by ry-oc — CHANGES_REQUESTED** [review]
When looking at this page from the front end the numbering is all funky, please can you correct it so that it makes sense.

The above can be achieved by fixing the indentation of the points below each number.

**Comment by TheAbstract** [comment]
@ry-oc I saw that on the site everything is numbered as 1, thought I fixed this cause the local version on this branch is showing correctly. Anyway, I updated the structure, take another look.

**Review by sheenarbw — APPROVED** [review]

**Pull request merged**
