### PR TITLE
added instruction for bonus part

### PR DESCRIPTION
**Pull request by AxelBankuna**
Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by kaleem99 — APPROVED** [review]

**Review by EckardBerry — APPROVED** [review]

**Review by ry-oc — CHANGES_REQUESTED** [review]
Please remove any unnecessary files, if you are adding text to a page there should only be one file changed

**Review by Vuyisanani — APPROVED** [review]

**Review by Sbonelo01 — CHANGES_REQUESTED** [review]
All looks good. There's just Merge conflicts

**Review by Sbonelo01 — APPROVED** [review]

**Review by ry-oc — CHANGES_REQUESTED** [review]
There is an additional file here that needs to be removed? content/projects/semitone-challenge/gui-part-2/._index.md.swp

**Review by sheenarbw — CHANGES_REQUESTED** [review]
There is a binary swp file in here.  Can you please delete it?

**Comment by ry-oc** [comment]
That's my bad, i made the change when i was busy reviewing this morning and forgot to push

**Review by Sbonelo01 — APPROVED** [review]

**Review by sheenarbw — APPROVED** [review]

**Pull request merged**
