### PR TITLE
added instructions for Semitone GUI part 2 

### LINKED ISSUE #85: Create "##Instructions for reviewer" for project: Semitone Difference - A gui that is more...awesome
Please add a section to the bottom of this project's _index.md file.
The section heading should be EXACTLY "## Instructions for reviewer"

Basically we have to set reviewers up for success by telling them what success looks like and what to pay attention to when reviewing this project submission.

Description:

- [ ] Look at a bunch of old reviews for this project for each cohort

- [ ] Find the common feedback [This should help you get an idea of what instructions to create]

- [ ] Write them out clearly

- [ ] The section heading should be EXACTLY "## Instructions for reviewer"

### PR DESCRIPTION
**Pull request by kaleem99**
Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by Sbonelo01 — COMMENTED** [review]
Any instructions related to the front-end/GUI ?

**Comment by ry-oc** [comment]
@kaleem99 , please make sure your PRs have descriptive names and that the related issues are linked if there are any

**Review by AxelBankuna — COMMENTED** [review]
It looks great. I'd like to have a session where we can discuss the placement of some of the punctuation marks.

**Review by EckardBerry — APPROVED** [review]

**Review by AxelBankuna — COMMENTED** [review]
`Ensure that the scorestreak gets incremented by 1 each time when a user guesses the correct answer and when the answer is not correct the scorestreak gets reset to 0.`:
The use of the word "guesses" implies that the game is a guessing game.

**Comment by AxelBankuna** [comment]
"To check if the code contains a bug call the function twice, have a print statement under it, and check if two notes are returned."
Suggestion:
"To check if the code contains a bug; call the function twice, have a print statement under it and check if two notes are returned."

"- Ensure that there are no unnecessary copying and pasting of variables, all variables used in different files should be exported and imported correctly."
Suggestion:
"- Ensure that there is no unnecessary copying and pasting of variables. All variables used in different files should be exported and imported correctly."

**Review by Lisa1400 — APPROVED** [review]

**Comment by Lisa1400** [comment]
@kaleem99 link the issue related to this PR.

**Review by AxelBankuna — APPROVED** [review]

**Review by ry-oc — APPROVED** [review]

**Review by sheenarbw — APPROVED** [review]

**Pull request merged**
